// <auto-generated />
using System;
using ComuniqueSe.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComuniqueSe.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622182642_AddAnexoPdf")]
    partial class AddAnexoPdf
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComuniqueSe.Api.Models.Historico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("PendenciaId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PendenciaId");

                    b.ToTable("Historicos");
                });

            modelBuilder.Entity("ComuniqueSe.Api.Models.Pendencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AtribuidoA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DivisaoCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Prazo")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProcessoId")
                        .HasColumnType("int");

                    b.Property<string>("Regionais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessoId");

                    b.ToTable("Pendencias");
                });

            modelBuilder.Entity("ComuniqueSe.Api.Models.Processo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnexoFase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("AnexoFaseArquivo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("AnexoFaseNome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnexoFaseTipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classificacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataEmissaoFase")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataValidadeFase")
                        .HasColumnType("datetime2");

                    b.Property<string>("DivisaoCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Empreendimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interessado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroFase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroProcesso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "processo");

                    b.Property<DateTime?>("Prazo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusFase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TecnicoResponsavel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Processos");
                });

            modelBuilder.Entity("ComuniqueSe.Api.Models.Trecho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Denominacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KmFinal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KmInicial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessoId")
                        .HasColumnType("int");

                    b.Property<string>("Rodovia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessoId");

                    b.ToTable("Trechos");
                });

            modelBuilder.Entity("ComuniqueSe.Api.Models.Historico", b =>
                {
                    b.HasOne("ComuniqueSe.Api.Models.Pendencia", null)
                        .WithMany("Historicos")
                        .HasForeignKey("PendenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComuniqueSe.Api.Models.Pendencia", b =>
                {
                    b.HasOne("ComuniqueSe.Api.Models.Processo", null)
                        .WithMany("Pendencias")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComuniqueSe.Api.Models.Trecho", b =>
                {
                    b.HasOne("ComuniqueSe.Api.Models.Processo", null)
                        .WithMany("Trechos")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComuniqueSe.Api.Models.Pendencia", b =>
                {
                    b.Navigation("Historicos");
                });

            modelBuilder.Entity("ComuniqueSe.Api.Models.Processo", b =>
                {
                    b.Navigation("Pendencias");

                    b.Navigation("Trechos");
                });
#pragma warning restore 612, 618
        }
    }
}
